name: Build and Deploy Blog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
    
    - name: List directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "\nDirectory structure:"
        ls -R
      
    - name: Build blog posts
      run: |
        echo "Python version:"
        python --version
        echo "\nRunning convert_posts.py:"
        python convert_posts.py
      
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push if changed
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected. Committing..."
          git add -A
          git commit -m "Auto-generate blog HTML files"
          git push
        else
          echo "No changes to commit"
        fi
