name: Build Blog

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'images/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'posts/**'
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
    
    - name: Build blog posts
      run: python convert_posts.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate blog HTML files" && git push)
